version: '3.8'

services:
  music-bot:
    build: .
    container_name: music-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APP_ID=${APP_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
    volumes:
      - ./economy.json:/app/economy.json
      - ./cache:/app/cache
